name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update -yq &&
          sudo apt-get install -yq python3-pip &&
          pip3 install --upgrade pip &&
          pip3 install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          pip3 install flake8 &&
          flake8 src
      
      - name: Run unit tests with nose
        run: |
          pip3 install nose coverage &&
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      
      - name: Basic vulnerability check
        run: |
          sudo apt-get install -yq curl &&
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin &&
          trivy --no-progress --exit-code 0 --severity HIGH,CRITICAL --no-progress --ignore-unfixed --input /requirements.txt
